server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: false
    fetch-registry: true

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
#          uri: http://localhost:8082
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: restaurant-app
          uri: lb://RESTAURANT-APP
#          uri: http://localhost:8081
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
#          uri: http://localhost:9898
          predicates:
            - Path=/auth/**